Arhiver for Haiku
HaikuArchives/Archiver pull request #1
Opened 2017-01-05 01:59 UTC by punsith

2017-01-05 02:18 UTC, scottmc commented
There is an option in Paladin to export a Makefile.  Do that and then the compiling step might be as easy as  running "make".

2017-01-05 02:29 UTC, punsith commented
okay :)

2017-01-11 14:33 UTC, punsith commented
i updated :)

2017-01-11 16:51 UTC, richienyhus commented
@scottmc & @waddlesplash any further changes needed ?

2017-01-12 12:38 UTC, pulkomandy requested changes

2017-01-12 12:38 UTC, pulkomandy commented on Source/Archiver.h
> +#include </boot/system/develop/headers/os/add-ons/tracker/TrackerAddOn.h>
This is not needed, keeping just <add-ons/tracker/TrackerAddOn.h> should work.

2017-01-12 12:38 UTC, pulkomandy commented on Source/Archiver.h
> +#define	ARCHIVER_RULES_FILE_PATH		"/boot/home/config/non-packaged/etc/"
I think it is better to look in the packaged directory? Or does it try to write here?
Ideally we should look in both but it is out of the scope of your task

2017-01-12 12:38 UTC, pulkomandy commented on drag _Archiver-A_ here
> +/boot/system/settings/etc
Are you sure this is where it goes? If it is a tracker add-on, then the proper place would be /boot/home/config/non-packaged/add-ons/Tracker

2017-01-12 20:08 UTC, punsith commented on Source/Archiver.h
> +#include </boot/system/develop/headers/os/add-ons/tracker/TrackerAddOn.h>
mm but it didn't compiled 
"boot/home/Archiver/Source/Archiver.h:54: /add-ons/tracker/TrackerAddOn.h: No such file or directory
/boot/system/develop/etc/makefile-engine:291: recipe for target 'objects.x86-gcc2-release/Archiver.o' failed
make: *** [objects.x86-gcc2-release/Archiver.o] Error 1
"

2017-01-12 20:23 UTC, punsith commented on Source/Archiver.h
> +#define	ARCHIVER_RULES_FILE_PATH		"/boot/home/config/non-packaged/etc/"
user should paste the rules file to that location but the program don't use the file on that location as Pete Goodeve said ,  it using rules file in " B_SYSTEM_ETC_DIRECTORY" . and also user should paste rules file on their but if I comment that  path it won't compile :/ but when i delete the rules file from non-packaged nothing changed :/

2017-01-27 18:52 UTC, scottmc commented
Any progress on cleaning this up?

2017-01-27 20:38 UTC, punsith commented
@scottmc 
 "ARCHIVER_RULES_FILE_PATH		"/boot/home/config/non-packaged/etc/""  
is something I cant understand. The archiver don't us the location above. It using .rules file in B_SYSTEM_ETC_DIRECTORY. but if I dete the  that code it wont work.

2017-12-27 04:47 UTC, closed without merging